### ISSUE TITLE
IPFS pin is required for go-ipfs to work

### ISSUE THREAD

**Issue by crazybuster** [OriginProtocol/origin-box#84]
https://github.com/OriginProtocol/origin-box/blob/3b3cd3e8ebb2ec0c3752cf5b69941f7527252e53/origin-messaging/src/insert-only-keystore.js#L58

I haven't really commented well, but the: 

//pinIPFS(message, signature, key)

That was here is actually very much needed if we're using go-ipfs(it's also broken in other ways though). So if we're going to use go-ipfs in the future this line here needs to be enable for that specific config scenario which I took out before because go-ipfs just was not working. The issue is that the pinIPFS code currently lives elsewhere and so need to be passed along somehow for this current structure to work(hence it being fairly flat and one file before).

**Comment by tomlinton** [comment]
Since we are using our own IPFS server and everything gets pinned if its added via the IPFS API wouldn't we automatically be pinning everything from OrbitDB? My understanding is that this would only be required if we didn't control the IPFS server.

Something to keep in mind if js-ipfs ever gets GC added.

**Comment by tomlinton** [comment]
Closing since we are using js-ipfs again.
